### ISSUE TITLE
Modal components are broken

### ISSUE THREAD

**Issue by turai** [iced-rs/iced_aw#114]
Same issue as in #73, examples/modal_components (https://github.com/iced-rs/iced_aw/commit/175b928380110bbf4d61361865f0dbe13ed8e108) can be used to reproduce:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:139:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/option.rs:949:21
   4: iced_lazy::component::Instance<Message,Renderer,Event,S>::rebuild_element_if_necessary::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:139:38
   5: iced_lazy::component::ouroboros_impl_state::State<Message,Renderer,Event,S>::new
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:94:1
   6: iced_lazy::component::ouroboros_impl_state::StateBuilder<Message,Renderer,Event,S,ElementBuilder_>::build
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:94:1
   7: iced_lazy::component::Instance<Message,Renderer,Event,S>::rebuild_element_if_necessary
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:146:18
   8: iced_lazy::component::Instance<Message,Renderer,Event,S>::with_element_mut
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:206:9
   9: iced_lazy::component::Instance<Message,Renderer,Event,S>::with_element
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:199:9
  10: <iced_lazy::component::Instance<Message,Renderer,Event,S> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:258:14
  11: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:169:17
  12: iced_native::widget::container::layout
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:309:23
  13: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:158:9
  14: <iced_aw::native::overlay::modal::ModalOverlay<Message,Renderer> as iced_native::overlay::Overlay<Message,Renderer>>::layout
             at /Users/turai/Development/iced_aw/src/native/overlay/modal.rs:81:27
  15: iced_native::overlay::element::Element<Message,Renderer>::layout
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/overlay/element.rs:62:9
  16: iced_native::user_interface::UserInterface<Message,Renderer>::update
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/user_interface.rs:208:30
  17: iced_winit::application::run_instance::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:424:44
  18: iced_winit::application::run::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:251:24
  19: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/app_state.rs:106:17
  20: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/app_state.rs:80:13
  21: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/app_state.rs:101:9
  22: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/app_state.rs:209:21
  23: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/app_state.rs:394:9
  24: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/observer.rs:184:21
  25: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/observer.rs:145:9
  26: std::panicking::try::do_call
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/std/src/panicking.rs:490:40
  27: std::panicking::try
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/std/src/panicking.rs:454:19
  28: std::panic::catch_unwind
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/std/src/panic.rs:140:14
  29: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/event_loop.rs:265:11
  30: winit::platform_impl::platform::observer::control_flow_handler
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/observer.rs:143:5
  31: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/observer.rs:179:9
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <() as objc::message::MessageArguments>::invoke
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
  43: objc::message::platform::send_unverified
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27:9
  44: objc::message::send_message
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178:5
  45: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/macros.rs:133:15
  46: objc::rc::autorelease::autoreleasepool
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/rc/autorelease.rs:29:5
  47: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/macos/event_loop.rs:212:25
  48: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform/run_return.rs:62:9
  49: iced_winit::application::platform::run
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:870:28
  50: iced_winit::application::run
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:226:5
  51: iced::application::Application::run
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced-0.9.0/src/application.rs:209:12
  52: iced::sandbox::Sandbox::run
             at /Users/turai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced-0.9.0/src/sandbox.rs:153:9
  53: modal_component::main
             at ./src/main.rs:9:5
  54: core::ops::function::FnOnce::call_once
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by genusistimelord** [comment]
yeah I know they are still broken but I still do not know Why it is broken as its been really hard to trace the reason for this. The example I have in there is to help trace and to know when it is finally fixed or not.

**Comment by turai** [comment]
My very shallow investigation suggests this doesn't really have anything to do with this crate, ran into the exact same panic while messing with my own components, but I'd rather keep this issue open to warn others.

**Comment by genusistimelord** [comment]
yeah that's fine. I suspect it has something to do with something Iced itself is doing but again its hard to track down. Like I can see where it error-ed but i cant see why it had an error.  Made me feel like something thread wise is missing data. Or something  ran before something else which made the data not yet appear. I will keep this comment open for others and ill point @hecrj  here too.

**Comment by TheComamba** [comment]
I ran into this some days ago and created an even more minimal example before discovering this issue. Just in case it might help, it can be found [here](https://github.com/TheComamba/LoreCore/tree/bug/iced-panic-minimal-example).

**Comment by TheComamba** [comment]
Preliminary analysis:

1. Modal::new calls the into() implementation of MyComponent.
2. into() is implemented via iced_lazy::component.
3. component() calls Element::new() in component.rs, setting tree to None.
4. I'm not sure how, but then diff() in modal.rs is called.
5. This in turn calls state() in component.rs, setting tree to Some. So far so good.
6. Then iced_nativ::user_interface::UserInterface::update calls Modal::overlay.
7. Here we call ModalOverlay::new(). One of the arguments is (self.content)(). I do not yet know that syntax, but it seems to call iced_lazy::component again. Is this some kind of typecast?
8. In any case, component(), calls Element::new() again and resets tree to None.
9. Still in UserInterface::update, we run into Element::layout().
10. This eventually calls Instance::rebuild_element_if_necessary in component.rs.
11. And now this function expects a tree to present, but because state was never called again since step 8, it is None.

**Comment by genusistimelord** [comment]
this seems like a iced issue then if it has to do when the state is being called. I wonder if there is something we can do to ensure the state is made and set.

**Comment by hecrj** [comment]
This is an `iced` issue. `Component` currently breaks the `Widget` contract. A proper fix isn't straightforward. I'll think about it.

In the meanwhile, we can call `Widget::diff` for the `content` before passing it to the `ModalOverlay` to ensure the widget tree has the proper state set.

**Comment by genusistimelord** [comment]
@turai  and @TheComamba can you please try the latest Main branch of iced_aw. I believe the new push fixes this issue.
